"""The 38 native in-game achievements, with stable IDs and access requirements."""
# Native ID, location label, required difficulty item, required potion type.
ACHIEVEMENTS = (
    ("WIN1", "Win 1 Run", None, None),
    ("WIN10", "Win 10 Runs", None, None),
    ("ClearNormal", "Clear Normal", None, None),
    ("ClearHard", "Clear Hard", "Hard Wedding", None),
    ("ClearNightmare", "Clear Nightmare", "Nightmare Wedding", None),
    ("LOSE1", "Lose 1 Run", None, None),
    ("LOSE10", "Lose 10 Runs", None, None),
    ("HitByGuardian", "Hit by Guardians 10 Times", None, None),
    ("Traveler", "Travel 1000 Units", None, None),
    ("Florist", "Collect 100 Flowers", None, None),
    ("TreasureHunter", "Break 100 Pumpkins", None, None),
    ("SkillMaster", "Use Skills 100 Times", None, None),
    ("Critical1000", "Land 1000 Critical Hits", None, None),
    ("Dodge100", "Dodge 100 Times", None, None),
    ("HPRegen100", "Regenerate HP 100 Times", None, None),
    ("Hit100", "Take 100 Hits", None, None),
    ("NoHitClear", "Clear with at Most 10 Hits", None, None),
    ("KILL1000", "Defeat 1000 Enemies", None, None),
    ("KILL10000", "Defeat 10000 Enemies", None, None),
    ("KILL20000", "Defeat 20000 Enemies", None, None),
    ("BlastMaster", "Master 10 Explosion Spells", None, None),
    ("MissileMaster", "Master 10 Missile Spells", None, None),
    ("MeleeMaster", "Master 10 Melee Spells", None, None),
    ("AreaMaster", "Master 10 Area Spells", None, None),
    ("FamiliarMaster", "Master 10 Familiar Spells", None, None),
    ("DarkMagicMaster", "Master 10 Curse Spells", None, None),
    ("Corruption10", "Drink 10 Corruption Potions", None, "Corruption"),
    ("BeastPotion10", "Drink 10 Beast Potions", None, "Beast"),
    ("BigBreastPotion10", "Drink 10 Big Breast Potions", None, "BigBreast"),
    ("MusclePotion10", "Drink 10 Muscle Potions", None, "Muscle"),
    ("HipPotion10", "Drink 10 Hip Potions", None, "Hip"),
    ("SmallBreastPotion10", "Drink 10 Small Breast Potions", None, "SmallBreast"),
    ("CorruptionPotionForm", "Fully Transform into Corruption", None, "Corruption"),
    ("BeastPotionForm", "Fully Transform into Beast", None, "Beast"),
    ("BigBreastPotionForm", "Fully Transform into Big Breasts", None, "BigBreast"),
    ("MusclePotionForm", "Fully Transform into Muscle", None, "Muscle"),
    ("HipPotionForm", "Fully Transform into Hips", None, "Hip"),
    ("SmallBreastPotionForm", "Fully Transform into Small Breasts", None, "SmallBreast"),
)

def achievement_location(label):
    return "Achievement: " + label
